import path from "path";
import fs from "fs-extra";
import { logger } from "./logger";

/**
 * Generates Fluent UI token CSS variables
 */
export async function generateTokenCss(
  projectDir: string,
  options: {
    outputPath?: string;
    format?: "css" | "scss";
  } = {}
): Promise<void> {
  const outputPath =
    options.outputPath ||
    path.join(projectDir, "src", "styles", "fluent-tokens.css");

  const format = options.format || "css";

  // Create basic token CSS
  const tokenCss = `/**
 * Fluent UI Design Tokens
 * Generated by Vindsmidi CLI
 */

:root {
  /* Brand Colors */
  --fluent-color-brand-background: #0f6cbd;
  --fluent-color-brand-background-hover: #115ea3;
  --fluent-color-brand-background-pressed: #0e4775;
  --fluent-color-brand-background-selected: #115ea3;
  
  /* Neutral Colors */
  --fluent-color-neutral-foreground-1: #242424;
  --fluent-color-neutral-foreground-2: #424242;
  --fluent-color-neutral-foreground-3: #616161;
  --fluent-color-neutral-foreground-disabled: #bdbdbd;
  
  --fluent-color-neutral-background-1: #ffffff;
  --fluent-color-neutral-background-2: #fafafa;
  --fluent-color-neutral-background-3: #f5f5f5;
  --fluent-color-neutral-background-4: #f0f0f0;
  --fluent-color-neutral-background-disabled: #f0f0f0;
  
  --fluent-color-neutral-stroke-1: #d1d1d1;
  --fluent-color-neutral-stroke-2: #e0e0e0;
  --fluent-color-neutral-stroke-3: #f0f0f0;
  --fluent-color-neutral-stroke-disabled: #e0e0e0;
  
  /* Border Radius */
  --fluent-border-radius-none: 0;
  --fluent-border-radius-small: 2px;
  --fluent-border-radius-medium: 4px;
  --fluent-border-radius-large: 6px;
  --fluent-border-radius-xlarge: 8px;
  --fluent-border-radius-circular: 9999px;
  
  /* Spacing */
  --fluent-spacing-xxs: 2px;
  --fluent-spacing-xs: 4px;
  --fluent-spacing-s: 8px;
  --fluent-spacing-m: 12px;
  --fluent-spacing-l: 16px;
  --fluent-spacing-xl: 20px;
  --fluent-spacing-xxl: 24px;
  --fluent-spacing-xxxl: 32px;
}

/* Dark Mode */
.dark-theme {
  --fluent-color-neutral-foreground-1: #ffffff;
  --fluent-color-neutral-foreground-2: #d6d6d6;
  --fluent-color-neutral-foreground-3: #adadad;
  --fluent-color-neutral-foreground-disabled: #616161;
  
  --fluent-color-neutral-background-1: #1a1a1a;
  --fluent-color-neutral-background-2: #242424;
  --fluent-color-neutral-background-3: #2e2e2e;
  --fluent-color-neutral-background-4: #383838;
  --fluent-color-neutral-background-disabled: #242424;
  
  --fluent-color-neutral-stroke-1: #575757;
  --fluent-color-neutral-stroke-2: #424242;
  --fluent-color-neutral-stroke-3: #383838;
  --fluent-color-neutral-stroke-disabled: #424242;
}
`;

  // Ensure directory exists
  await fs.ensureDir(path.dirname(outputPath));

  // Write token CSS
  await fs.writeFile(outputPath, tokenCss);
  logger.success(
    `Generated token CSS at ${path.relative(process.cwd(), outputPath)}`
  );

  // Create import for main CSS
  const mainCssPath = path.join(path.dirname(outputPath), "main.css");

  if (await fs.pathExists(mainCssPath)) {
    const mainCss = await fs.readFile(mainCssPath, "utf8");

    if (!mainCss.includes("fluent-tokens.css")) {
      const updatedMainCss = `@import "./fluent-tokens.css";\n${mainCss}`;
      await fs.writeFile(mainCssPath, updatedMainCss);
      logger.success("Updated main.css to import token CSS");
    }
  }
}
